# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd417002b1e4e9807e3f51112f7464a23f21532d010cdf0ef45eb2c3c83f09dd1155f1876e7094d307b0d61640a50fd642fd72994610dceb6901c50d6499cad

test:
  secret_key_base: e48c7dda3e9baecb5db881b83a7d30bfafff790ac5c95fa5bd3d4ee2b85d264097bbdda8ec47dd91d2d14b60332ee43c2fc6c447f9476a108a1ef67dad4e63e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
